version: '3'
services:
  app:
      build: .
      volumes:
      - .:/app
      - ~/.m2:/root/.m2
      working_dir: /app
      ports:
      - "8080:8080"
      command: mvn clean spring-boot:run
      depends_on:
      - bravi-mysql
      restart: always
      networks:
      - net-backend

  bravi-mysql:
    container_name: bravi-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: contact_list
      MYSQL_ROOT_PASSWORD: pedro.meireles
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    networks:
      - net-backend

networks:
  net-backend:
